package lesson26_thread;

import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

public class BingoJFrame extends javax.swing.JFrame {
    
    ImageIcon apple = new ImageIcon(getClass().getResource("/lesson26_thread/apple.png"));
    ImageIcon bar = new ImageIcon(getClass().getResource("/lesson26_thread/bar.png"));
    ImageIcon bell = new ImageIcon(getClass().getResource("/lesson26_thread/bell.png"));
    ImageIcon mango = new ImageIcon(getClass().getResource("/lesson26_thread/mango.png"));
    ImageIcon orange = new ImageIcon(getClass().getResource("/lesson26_thread/orange.png"));
    ImageIcon seven = new ImageIcon(getClass().getResource("/lesson26_thread/seven.png"));
    ImageIcon star = new ImageIcon(getClass().getResource("/lesson26_thread/star.png"));
    ImageIcon watermelon = new ImageIcon(getClass().getResource("/lesson26_thread/watermelon.png"));
    
    ImageIcon[] icons = {apple, bar, bell, mango, orange, seven, star, watermelon};
    
    class BingoRun implements Runnable {
        private JLabel n;
        private int idx;
        public BingoRun(JLabel n) {
            this.n = n;
        }

        public int getIdx() {
            return idx;
        }
        
        @Override
        public void run() {
            
            for(int i=1;i<=1000;i++) {
                idx = new Random().nextInt(icons.length);
                n.setIcon(icons[idx]);
                try {
                    Thread.sleep(1);
                } catch (InterruptedException ex) {
                }
            }
            
        }
    }
    
    public BingoJFrame() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        n1 = new javax.swing.JLabel();
        n2 = new javax.swing.JLabel();
        n3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("賓果遊戲");

        n1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lesson26_thread/apple.png"))); // NOI18N

        n2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lesson26_thread/apple.png"))); // NOI18N

        n3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lesson26_thread/apple.png"))); // NOI18N

        jButton1.setFont(new java.awt.Font("新細明體", 0, 24)); // NOI18N
        jButton1.setText("Play");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(n1)
                        .addGap(47, 47, 47)
                        .addComponent(n2)
                        .addGap(43, 43, 43)
                        .addComponent(n3)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(n1)
                    .addComponent(n2)
                    .addComponent(n3))
                .addGap(51, 51, 51)
                .addComponent(jButton1)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        BingoRun br1 = new BingoRun(n1);
        BingoRun br2 = new BingoRun(n2);
        BingoRun br3 = new BingoRun(n3);
        
        Thread t1 = new Thread(br1);
        Thread t2 = new Thread(br2);
        Thread t3 = new Thread(br3);
        
        t1.start();
        t2.start();
        t3.start();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BingoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BingoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BingoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BingoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BingoJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel n1;
    private javax.swing.JLabel n2;
    private javax.swing.JLabel n3;
    // End of variables declaration//GEN-END:variables
}
